// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqqhgywfrkmalheveort.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcWhneXdmcmttYWxoZXZlb3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTY4MjcsImV4cCI6MjA2NzIzMjgyN30.78otLN0SYff_rhIMpLRLDkqao0yTPCOOwUvWBkizZw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});